### ISSUE TITLE
Crash after 3.8 update

### ISSUE THREAD

**Issue by VanheXen** [Xm798/Genshin-Dailynote-Reminder#1]
### 问题描述

After the 3.8 update, the container crashes at startup, i tried a new cookie that is working in other things so the cookie is ok

### 运行环境

Docker

### 程序版本

v2.2.1

### 复现流程

At startup after 3.8 update

### 完整日志

```shell
2023-07-07 23:24:46 2023-07-07 23:24:46 INFO 
2023-07-07 23:24:46 -------------------------------------------------------------
2023-07-07 23:24:46 |                Genshin Dailynote Helper                   |
2023-07-07 23:24:46 -------------------------------------------------------------
2023-07-07 23:24:46 | Current Version: v2.2.1                                   |
2023-07-07 23:24:46 | Last Update: Nov 25, 2022                                 |
2023-07-07 23:24:46 | Github: https://github.com/Xm798/Genshin-Dailynote-Helper |
2023-07-07 23:24:46 -------------------------------------------------------------
2023-07-07 23:24:46 
2023-07-07 23:24:46 2023-07-07 23:24:46 INFO 🗝️ Currently 1 accounts are configured, and 1th is being executed
2023-07-07 23:24:46 2023-07-07 23:24:46 INFO -------------------------
2023-07-07 23:24:46 2023-07-07 23:24:46 INFO Getting game roles information
2023-07-07 23:24:47 2023-07-07 23:24:47 INFO 获取到oversea server的1个角色...
2023-07-07 23:24:47 2023-07-07 23:24:47 INFO The 1th character, xxxxxxxxx xxx
2023-07-07 23:24:48 Traceback (most recent call last):
2023-07-07 23:24:48   File "./index.py", line 3, in <module>
2023-07-07 23:24:48     run()
2023-07-07 23:24:48   File "/app/dailynotehelper/__init__.py", line 25, in run
2023-07-07 23:24:48     run_once()
2023-07-07 23:24:48   File "/app/dailynotehelper/__init__.py", line 19, in run_once
2023-07-07 23:24:48     start(config.COOKIE_HOYOLAB, 'os')
2023-07-07 23:24:48   File "/app/dailynotehelper/check.py", line 215, in start
2023-07-07 23:24:48     check.standard_mode(client, role, True)
2023-07-07 23:24:48   File "/app/dailynotehelper/check.py", line 169, in standard_mode
2023-07-07 23:24:48     info = client.parse_dailynote_info(role)
2023-07-07 23:24:48   File "/app/dailynotehelper/getinfo/client.py", line 75, in parse_dailynote_info
2023-07-07 23:24:48     result = parse_info(data, role, mode='standard')
2023-07-07 23:24:48   File "/app/dailynotehelper/getinfo/parse_info.py", line 52, in parse_info
2023-07-07 23:24:48     result.append(get_expedition_info(info))
2023-07-07 23:24:48   File "/app/dailynotehelper/getinfo/parse_info.py", line 163, in get_expedition_info
2023-07-07 23:24:48     r'(?<=(UI_AvatarIcon_Side_)).*(?=.png)', expedition['avatar_side_icon']
2023-07-07 23:24:48 AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by Xm798** [comment]
The reason is that miHoYo changed the return values for the dispatch information. I'm sorry it took so long to fix, but it should work normally in version 2.3.
