### ISSUE TITLE
Crash when locale set to en_US

### ISSUE THREAD

**Issue by VanheXen** [Xm798/Genshin-Dailynote-Reminder#14]
### 问题描述

After updating, setting the locale to en_US via the config file crashes the docker container.

### 运行环境

Docker

### 程序版本

2.1.14

### 复现流程

Set locale to en_US

### 完整日志

```shell
Traceback (most recent call last):
  File "./index.py", line 3, in <module>
    run()
  File "/app/dailynotehelper/__init__.py", line 25, in run
    run_once()
  File "/app/dailynotehelper/__init__.py", line 19, in run_once
    start(config.COOKIE_HOYOLAB, 'os')
  File "/app/dailynotehelper/check.py", line 175, in start
    dailynote_info, message = client.prase_dailynote_info(role)
  File "/app/dailynotehelper/getinfo/client.py", line 99, in prase_dailynote_info
    result = prase_info(self.dailynote_info, role)
  File "/app/dailynotehelper/getinfo/praseinfo.py", line 47, in prase_info
    result.append(get_expedition_info(base_data))
  File "/app/dailynotehelper/getinfo/praseinfo.py", line 121, in get_expedition_info
    avatar_json = json.load(f)
  File "/usr/local/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 14 column 1 (char 327)
```

**Comment by Xm798** [comment]
Oops, so sorry for that.
Fixed in [v2.1.15](https://github.com/Xm798/Genshin-Dailynote-Reminder/releases/tag/v2.1.15) and you can repull the docker image.
Thanks.
