### ISSUE TITLE
推送讯息突然报错

### ISSUE THREAD

**Issue by stevened7246** [Xm798/Genshin-Dailynote-Reminder#5]
### 问题描述

就突然推送报错

### 运行环境

Docker

### 程序版本

2.1.8.2或者2.1.9？

### 复现流程

未知

### 完整日志

```shell
2022-08-07 12:03:22 INFO 🗝️ 目前配置了1個帳號，正在執行第1個
2022-08-07 12:03:22 INFO -------------------------
2022-08-07 12:03:22 INFO 正在獲取角色資料
2022-08-07 12:03:23 INFO 獲取到國際服的2個角色...
2022-08-07 12:03:23 INFO 第1個角色，618705912 玩家618705912
2022-08-07 12:03:23 INFO 跳過該角色
2022-08-07 12:03:23 INFO 第2個角色，900545313 輕若羽雨
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "./index.py", line 3, in <module>
    run()
  File "/app/dailynotehelper/__init__.py", line 214, in run
    schedule.run_pending()
  File "/usr/local/lib/python3.7/site-packages/schedule/__init__.py", line 780, in run_pending
    default_scheduler.run_pending()
  File "/usr/local/lib/python3.7/site-packages/schedule/__init__.py", line 100, in run_pending
    self._run_job(job)
  File "/usr/local/lib/python3.7/site-packages/schedule/__init__.py", line 172, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.7/site-packages/schedule/__init__.py", line 661, in run
    ret = self.job_func()
  File "/app/dailynotehelper/__init__.py", line 205, in run_once
    start(config.COOKIE_HOYOLAB, 'os')
  File "/app/dailynotehelper/__init__.py", line 181, in start
    dailynote_info, message = client.prase_dailynote_info(role)
  File "/app/dailynotehelper/getinfo/client.py", line 82, in prase_dailynote_info
    self._get_dailynote_info(role['game_uid'], role['region'])
  File "/app/dailynotehelper/getinfo/client.py", line 78, in _get_dailynote_info
    log.error(response.retcode, response.message)
Message: 1009
Arguments: ('角色信息错误',)
2022-08-07 12:03:29 INFO Discord 🥳
2022-08-07 12:03:29 INFO -------------------------
2022-08-07 12:03:29 INFO 本輪執行結束，等待下次檢查...
```

### 其他补充说明

盲猜米忽悠黑锅

**Comment by Xm798** [comment]
可复现，原因为米哈游不知何时悄咪咪换了 API 地址，并且今天把旧 API 停掉了。已推送修复，docker [自动构建中](https://github.com/Xm798/Genshin-Dailynote-Reminder/actions/runs/2811960581)，稍后拉取最新镜像测试即可。
